### ISSUE TITLE
 Unknown:  RuntimeError: Cannot make context: this context is already current on another thread.

### ISSUE THREAD

**Issue by noobitard** [google-research/pisac#3]
Hi.

Thanks for releasing your code. I'm trying to run the code for cartpole_swingup with the default parameters and the command from README. However, there is an error:

```
Unknown: RuntimeError: Cannot make context <dm_control._render.pyopengl.egl_renderer.EGLContext object at 0x7f72e010e970> current on thread <_DummyThread(Dummy-10, started daemon 140127401670400)>: this context is already current on another thread <_DummyThread(Dummy-9, started daemon 140127393277696)>.
Traceback (most recent call last):

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/tf_py_environment.py", line 318, in _isolated_step_py
    return self._execute(_step_py, *flattened_actions)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/tf_py_environment.py", line 214, in _execute
    return fn(*args, **kwargs)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/tf_py_environment.py", line 314, in _step_py
    self._time_step = self._env.step(packed)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/py_environment.py", line 203, in step
    self._current_time_step = self._step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/batched_py_environment.py", line 166, in _step
    time_steps = self._envs[0].step(actions)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/py_environment.py", line 203, in step
    self._current_time_step = self._step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/wrappers.py", line 117, in _step
    time_step = self._env.step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/py_environment.py", line 203, in step
    self._current_time_step = self._step(action)

  File "/home/hue/Documents/anhdd14/pisac/pisac/dm_control_env.py", line 194, in _step
    time_step = self._env.step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/py_environment.py", line 203, in step
    self._current_time_step = self._step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/wrappers.py", line 213, in _step
    time_step = self._env.step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/py_environment.py", line 203, in step
    self._current_time_step = self._step(action)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/tf_agents/environments/dm_control_wrapper.py", line 91, in _step
    return convert_time_step(self._env.step(action))

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/dm_control/suite/wrappers/pixels.py", line 98, in step
    return self._add_pixel_observation(time_step)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/dm_control/suite/wrappers/pixels.py", line 115, in _add_pixel_observation
    pixels = self._env.physics.render(**self._render_kwargs)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 213, in render
    camera = Camera(

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 664, in __init__
    with self._physics.contexts.gl.make_current() as ctx:

  File "/opt/miniconda/envs/dreamer/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)

  File "/opt/miniconda/envs/dreamer/lib/python3.8/site-packages/dm_control/_render/base.py", line 116, in make_current
    raise RuntimeError(

RuntimeError: Cannot make context <dm_control._render.pyopengl.egl_renderer.EGLContext object at 0x7f72e010e970> current on thread <_DummyThread(Dummy-10, started daemon 140127401670400)>: this context is already current on another thread <_DummyThread(Dummy-9, started daemon 140127393277696)>.
```

Do you know why this is happening? I'm using Ubuntu 18.04.4 LTS and Python 3.8.3 with Conda. I have tried to change the isolation parameter of TFPyEnvironment call to True to make the env run on a thread, and the training process can run. However when it comes to the eval env, the error appear again.

**Comment by kuanghuei** [comment]
This is a known issue with dm control. You can follow the Requirements section of README and set --gin_bindings=train_pisac.train_eval.drivers_in_graph=False. Please reopen if it doesn't work.
